// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LeetCodeVsExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "LeetCodeVsExtension.1b52c717-f88c-4869-8477-521d3fef1817";
        public const string Name = "LeetCodeVsExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "code is happy";
        public const string Tags = "";
    }
}
